
timezone: Asia/Dhaka
email: ahm@disroot.org
github_username:  ahmubashshir
twitter_username: ahmubashshir
kramdown:
  input: GFM
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - vendor
  - LICENSE.md
  - README.md
